const FLAGS: Record<string, string> = {
  // UEFA
  Germany: '🇩🇪',
  France: '🇫🇷',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Spain: '🇪🇸',
  Portugal: '🇵🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Italy: '🇮🇹',
  Switzerland: '🇨🇭',
  Croatia: '🇭🇷',
  Serbia: '🇷🇸',
  Denmark: '🇩🇰',
  Austria: '🇦🇹',
  Turkey: '🇹🇷',
  Hungary: '🇭🇺',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Norway: '🇳🇴',
  Sweden: '🇸🇪',
  Czechia: '🇨🇿',
  'Bosnia-Herzegovina': '🇧🇦',
  // CONMEBOL
  Argentina: '🇦🇷',
  Brazil: '🇧🇷',
  Colombia: '🇨🇴',
  Uruguay: '🇺🇾',
  Ecuador: '🇪🇨',
  Chile: '🇨🇱',
  Paraguay: '🇵🇾',
  Bolivia: '🇧🇴',
  // AFC
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Iran: '🇮🇷',
  'IR Iran': '🇮🇷',
  Australia: '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  Uzbekistan: '🇺🇿',
  Jordan: '🇯🇴',
  Iraq: '🇮🇶',
  Qatar: '🇶🇦',
  // CAF
  Morocco: '🇲🇦',
  Senegal: '🇸🇳',
  Nigeria: '🇳🇬',
  Egypt: '🇪🇬',
  Cameroon: '🇨🇲',
  'South Africa': '🇿🇦',
  'Ivory Coast': '🇨🇮',
  Ghana: '🇬🇭',
  Tunisia: '🇹🇳',
  Algeria: '🇩🇿',
  'Congo DR': '🇨🇩',
  'Cape Verde Islands': '🇨🇻',
  // CONCACAF
  'United States': '🇺🇸',
  USA: '🇺🇸',
  Mexico: '🇲🇽',
  Canada: '🇨🇦',
  Jamaica: '🇯🇲',
  Panama: '🇵🇦',
  Honduras: '🇭🇳',
  Haiti: '🇭🇹',
  'Curaçao': '🇨🇼',
  // OFC
  'New Zealand': '🇳🇿',
  Indonesia: '🇮🇩',
};

export function getFlag(team: string): string {
  return FLAGS[team] ?? '🏳';
}
